### ISSUE TITLE
Video now private

### ISSUE THREAD

**Issue by sidharthmirch** [CT83/Hemuer#6]
wrong embed? 
<iframe width="1430" height="969" src="https://www.youtube.com/embed/35_FVzA0XU0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

**Comment by CT83** [comment]
Yep yep! The entire project is broken! :( Too busy to fix things. You want to give it a go?
